services:
  fhir:
    depends_on:
    - autoinstrumentation
    environment:
      NODE_OPTIONS: '--require /otel-auto-instrumentation-nodejs/autoinstrumentation.js'
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel:4317
      OTEL_NODE_ENABLED_INSTRUMENTATIONS: dataloader,express,graphql,lru-memoizer,router,winston,http,mongodb
    volumes:
    - autoinstrumentation:/otel-auto-instrumentation-nodejs

  autoinstrumentation:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:0.53.0
    command:
    - cp
    - -r
    - /autoinstrumentation/.
    - /otel-auto-instrumentation-nodejs
    volumes:
    - autoinstrumentation:/otel-auto-instrumentation-nodejs

  otel:
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib
    volumes:
    - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail http://otel:13133/ || exit 1" ]

volumes:
  autoinstrumentation:
